name: Test patches integration

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILDDIR: "/tmp/build"

jobs:
  test-integration:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel
      volumes:
        - /tmp:/tmp
    steps:
      - uses: actions/checkout@v3
      - name:
        shell: bash
        run: |
          df -h
          df -hk /tmp
      - name: Create build user
        run: |
          useradd -m build
          mkdir -p /tmp/src
          cp -vR linux /tmp/src/linux
          chown -vR build /tmp/src/linux
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm bc cpio pahole python kmod
          pacman -Scc --noconfirm
      - name: Prepare sources
        shell: bash
        run: |
          su build bash -c "cd /tmp/src/linux && makepkg --nobuild"
      - name:
        shell: bash
        run: |
          df -h
          df -hk /tmp

