name: Test patches integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            linux
      - name:
        run: |
          pwd
      - name:
        shell: bash
        run: |
          df -h
          df -k /tmp

  test-integration:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            linux
          fetch-depth: 1
      - name:
        shell: bash
        run: |
          pwd
      - name:
        shell: bash
        run: |
          df -h
          df -k /tmp
      - name: Create build user
        run: |
          useradd -m build
          chown -vR build .
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm bc cpio pahole python kmod
          pacman -Scc --noconfirm
      - name: Prepare sources
        shell: bash
        run: |
          su build bash -c "cd linux && makepkg --nobuild"
      - name:
        shell: bash
        run: |
          df -h
          df -hk /tmp

